name: voice_conversation_app
description: Flutter voice conversation app with OpenAI Whisper and Cartesia TTS

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: ">=3.10.0"

dependencies:
  flutter:
    sdk: flutter
  
  # WebSocket communication with Python backend
  socket_io_client: ^2.0.3+1
  
  # Audio recording and playback
  record: ^5.0.4
  audioplayers: ^5.2.1
  
  # Permissions
  permission_handler: ^11.0.1
  
  # HTTP requests
  dio: ^5.3.2
  
  # UI and state management
  cupertino_icons: ^1.0.2
  provider: ^6.0.5
  
  # Utilities
  uuid: ^4.1.0
  path_provider: ^2.1.1
  convert: ^3.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true