 name: voice_conversation_app
description: Flutter voice conversation app with WebSocket streaming

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: ">=3.10.0"

dependencies:
  flutter:
    sdk: flutter
  
  # WebSocket and networking
  web_socket_channel: ^2.4.0
  dio: ^5.3.2
  
  # Audio streaming and playback
  just_audio: ^0.9.34
  audio_streams: ^0.2.0
  
  # Speech recognition
  speech_to_text: ^6.3.0
  permission_handler: ^11.0.1
  
  # UI and state management
  cupertino_icons: ^1.0.2
  provider: ^6.0.5
  
  # Utilities
  uuid: ^4.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true